oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix: /platform

oc_platform_home:
    path: /     
    defaults: { _controller: OCPlatformBundle:Advert:index }
    
oc_platform_view:
    path: /advert/{id}
    defaults: { _controller: OCPlatformBundle:Advert:view }

oc_platform_view_slug:
    path: /{year}/{slug}.{_format}
    defaults:
        _controller: OCPlatformBundle:Advert:viewSlug
        _format: html
    requirements:
        year: \d{4}
        _format: html|xml

oc_platform_add:
    path: /add
    defaults: { _controller: OCPlatformBundle:Advert:add }

byebye_the_world:
    path:     /byebye-world
    defaults: { _controller: OCPlatformBundle:Advert:byebye }
